CREATE DATABASE HIGHPERKAI

USE HIGHPERKAI

DROP TABLE IF EXISTS ATLETA
DROP TABLE IF EXISTS ENTRENADOR
DROP TABLE IF EXISTS ACTIVIDAD
DROP TABLE IF EXISTS RESULTADOS
DROP TABLE IF EXISTS INGREDIENTE
DROP TABLE IF EXISTS CUENTA
DROP TABLE IF EXISTS RUTINA
DROP TABLE IF EXISTS MENU

CREATE TABLE CUENTA
(NoCuenta INT NOT NULL,
Correo VARCHAR(100) NOT NULL,
Contraseña VARCHAR(20) NOT NULL,
TipoCuenta CHAR(1) NOT NULL
PRIMARY KEY (NoCuenta)
)

CREATE TABLE RUTINA
(IDRutina INT NOT NULL,
Nombre VARCHAR(200) NOT NULL,
Descripcion VARCHAR(5000) NOT NULL,
Intensidad VARCHAR(10) NOT NULL,
Duracion TIME NOT NULL,
Calorias INT NOT NULL,
Compleatada CHAR(1)
PRIMARY KEY(IDRutina)
)

CREATE TABLE ATLETA
(NoAtleta INT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Estatura INT NOT NULL,
Peso FLOAT(2) NOT NULL,
Deporte VARCHAR(20) NOT NULL,
Foto IMAGE,
NoCuenta INT FOREIGN KEY REFERENCES CUENTA(NoCuenta),
IDRutina INT FOREIGN KEY REFERENCES RUTINA(IDRutina)
PRIMARY KEY (NoAtleta)
)

CREATE TABLE ENTRENADOR
(NoEntrenador INT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Deporte VARCHAR(20) NOT NULL,
Foto IMAGE,
NoCuenta INT FOREIGN KEY REFERENCES CUENTA(NoCuenta),
IDRutina INT FOREIGN KEY REFERENCES RUTINA(IDRutina)
PRIMARY KEY (NoEntrenador)
)

CREATE TABLE ACTIVIDAD
(IDActividad INT NOT NULL,
Nombre VARCHAR(200) NOT NULL,
Descripcion VARCHAR(5000) NOT NULL,
Sesiones INT NOT NULL,
Duracion INT NOT NULL,
Fecha DATE NOT NULL,
Calorias INT NOT NULL,
Completado CHAR(1),
IDRutina INT FOREIGN KEY REFERENCES RUTINA(IDRutina)
)

CREATE TABLE RESULTADOS
(RutinasCompletadas INT NOT NULL,
ActividadesCompletadas INT NOT NULL,
HorasAcumuladas INT NOT NULL,
CaloriasAcumuladas INT NOT NULL,
NoAtleta INT FOREIGN KEY REFERENCES ATLETA(NoAtleta)
)

CREATE TABLE MENU
(IDMenu INT NOT NULL,
Nombre VARCHAR(200) NOT NULL,
Descripcion VARCHAR(5000) NOT NULL,
Calorias INT NOT NULL,
Patlillo VARCHAR(5) NOT NULL
PRIMARY KEY (IDMenu)
)

CREATE TABLE INGREDIENTE
(Nombre VARCHAR(200) NOT NULL,
Cantidad VARCHAR(50) NOT NULL,
IDMenu INT FOREIGN KEY REFERENCES MENU(IDMenu)
)